name: CI

on:
  push:
    branches: [ master, 'spec-*', 'km/*' ]
  pull_request:
    branches: [ master, 'spec-*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
#        java: [11, 17, 21]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'corretto'
    
#    - name: Cache Maven dependencies
#      uses: actions/cache@v4
#      with:
#        path: ~/.m2
#        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#        restore-keys: |
#          ${{ runner.os }}-m2-
    
    - name: Build with Maven
      run: mvn clean compile -B -V
    
    - name: Run tests
      run: mvn verify -B
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (Java ${{ matrix.java }})
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit
        fail-on-error: true